// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/c2micro/c2msrv/internal/ent/blobber"
	"github.com/c2micro/c2msrv/internal/ent/predicate"
	"github.com/c2micro/c2msrv/internal/ent/task"
)

// BlobberQuery is the builder for querying Blobber entities.
type BlobberQuery struct {
	config
	ctx            *QueryContext
	order          []blobber.OrderOption
	inters         []Interceptor
	predicates     []predicate.Blobber
	withTaskArgs   *TaskQuery
	withTaskOutput *TaskQuery
	modifiers      []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BlobberQuery builder.
func (bq *BlobberQuery) Where(ps ...predicate.Blobber) *BlobberQuery {
	bq.predicates = append(bq.predicates, ps...)
	return bq
}

// Limit the number of records to be returned by this query.
func (bq *BlobberQuery) Limit(limit int) *BlobberQuery {
	bq.ctx.Limit = &limit
	return bq
}

// Offset to start from.
func (bq *BlobberQuery) Offset(offset int) *BlobberQuery {
	bq.ctx.Offset = &offset
	return bq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bq *BlobberQuery) Unique(unique bool) *BlobberQuery {
	bq.ctx.Unique = &unique
	return bq
}

// Order specifies how the records should be ordered.
func (bq *BlobberQuery) Order(o ...blobber.OrderOption) *BlobberQuery {
	bq.order = append(bq.order, o...)
	return bq
}

// QueryTaskArgs chains the current query on the "task_args" edge.
func (bq *BlobberQuery) QueryTaskArgs() *TaskQuery {
	query := (&TaskClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blobber.Table, blobber.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, blobber.TaskArgsTable, blobber.TaskArgsColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTaskOutput chains the current query on the "task_output" edge.
func (bq *BlobberQuery) QueryTaskOutput() *TaskQuery {
	query := (&TaskClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blobber.Table, blobber.FieldID, selector),
			sqlgraph.To(task.Table, task.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, blobber.TaskOutputTable, blobber.TaskOutputColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Blobber entity from the query.
// Returns a *NotFoundError when no Blobber was found.
func (bq *BlobberQuery) First(ctx context.Context) (*Blobber, error) {
	nodes, err := bq.Limit(1).All(setContextOp(ctx, bq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{blobber.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bq *BlobberQuery) FirstX(ctx context.Context) *Blobber {
	node, err := bq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Blobber ID from the query.
// Returns a *NotFoundError when no Blobber ID was found.
func (bq *BlobberQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bq.Limit(1).IDs(setContextOp(ctx, bq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{blobber.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bq *BlobberQuery) FirstIDX(ctx context.Context) int {
	id, err := bq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Blobber entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Blobber entity is found.
// Returns a *NotFoundError when no Blobber entities are found.
func (bq *BlobberQuery) Only(ctx context.Context) (*Blobber, error) {
	nodes, err := bq.Limit(2).All(setContextOp(ctx, bq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{blobber.Label}
	default:
		return nil, &NotSingularError{blobber.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bq *BlobberQuery) OnlyX(ctx context.Context) *Blobber {
	node, err := bq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Blobber ID in the query.
// Returns a *NotSingularError when more than one Blobber ID is found.
// Returns a *NotFoundError when no entities are found.
func (bq *BlobberQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = bq.Limit(2).IDs(setContextOp(ctx, bq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{blobber.Label}
	default:
		err = &NotSingularError{blobber.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bq *BlobberQuery) OnlyIDX(ctx context.Context) int {
	id, err := bq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Blobbers.
func (bq *BlobberQuery) All(ctx context.Context) ([]*Blobber, error) {
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryAll)
	if err := bq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Blobber, *BlobberQuery]()
	return withInterceptors[[]*Blobber](ctx, bq, qr, bq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bq *BlobberQuery) AllX(ctx context.Context) []*Blobber {
	nodes, err := bq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Blobber IDs.
func (bq *BlobberQuery) IDs(ctx context.Context) (ids []int, err error) {
	if bq.ctx.Unique == nil && bq.path != nil {
		bq.Unique(true)
	}
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryIDs)
	if err = bq.Select(blobber.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bq *BlobberQuery) IDsX(ctx context.Context) []int {
	ids, err := bq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bq *BlobberQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryCount)
	if err := bq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bq, querierCount[*BlobberQuery](), bq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bq *BlobberQuery) CountX(ctx context.Context) int {
	count, err := bq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bq *BlobberQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryExist)
	switch _, err := bq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bq *BlobberQuery) ExistX(ctx context.Context) bool {
	exist, err := bq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BlobberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bq *BlobberQuery) Clone() *BlobberQuery {
	if bq == nil {
		return nil
	}
	return &BlobberQuery{
		config:         bq.config,
		ctx:            bq.ctx.Clone(),
		order:          append([]blobber.OrderOption{}, bq.order...),
		inters:         append([]Interceptor{}, bq.inters...),
		predicates:     append([]predicate.Blobber{}, bq.predicates...),
		withTaskArgs:   bq.withTaskArgs.Clone(),
		withTaskOutput: bq.withTaskOutput.Clone(),
		// clone intermediate query.
		sql:  bq.sql.Clone(),
		path: bq.path,
	}
}

// WithTaskArgs tells the query-builder to eager-load the nodes that are connected to
// the "task_args" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BlobberQuery) WithTaskArgs(opts ...func(*TaskQuery)) *BlobberQuery {
	query := (&TaskClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withTaskArgs = query
	return bq
}

// WithTaskOutput tells the query-builder to eager-load the nodes that are connected to
// the "task_output" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BlobberQuery) WithTaskOutput(opts ...func(*TaskQuery)) *BlobberQuery {
	query := (&TaskClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withTaskOutput = query
	return bq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Blobber.Query().
//		GroupBy(blobber.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bq *BlobberQuery) GroupBy(field string, fields ...string) *BlobberGroupBy {
	bq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BlobberGroupBy{build: bq}
	grbuild.flds = &bq.ctx.Fields
	grbuild.label = blobber.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Blobber.Query().
//		Select(blobber.FieldCreatedAt).
//		Scan(ctx, &v)
func (bq *BlobberQuery) Select(fields ...string) *BlobberSelect {
	bq.ctx.Fields = append(bq.ctx.Fields, fields...)
	sbuild := &BlobberSelect{BlobberQuery: bq}
	sbuild.label = blobber.Label
	sbuild.flds, sbuild.scan = &bq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BlobberSelect configured with the given aggregations.
func (bq *BlobberQuery) Aggregate(fns ...AggregateFunc) *BlobberSelect {
	return bq.Select().Aggregate(fns...)
}

func (bq *BlobberQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bq); err != nil {
				return err
			}
		}
	}
	for _, f := range bq.ctx.Fields {
		if !blobber.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bq.path != nil {
		prev, err := bq.path(ctx)
		if err != nil {
			return err
		}
		bq.sql = prev
	}
	return nil
}

func (bq *BlobberQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Blobber, error) {
	var (
		nodes       = []*Blobber{}
		_spec       = bq.querySpec()
		loadedTypes = [2]bool{
			bq.withTaskArgs != nil,
			bq.withTaskOutput != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Blobber).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Blobber{config: bq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(bq.modifiers) > 0 {
		_spec.Modifiers = bq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bq.withTaskArgs; query != nil {
		if err := bq.loadTaskArgs(ctx, query, nodes,
			func(n *Blobber) { n.Edges.TaskArgs = []*Task{} },
			func(n *Blobber, e *Task) { n.Edges.TaskArgs = append(n.Edges.TaskArgs, e) }); err != nil {
			return nil, err
		}
	}
	if query := bq.withTaskOutput; query != nil {
		if err := bq.loadTaskOutput(ctx, query, nodes,
			func(n *Blobber) { n.Edges.TaskOutput = []*Task{} },
			func(n *Blobber, e *Task) { n.Edges.TaskOutput = append(n.Edges.TaskOutput, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bq *BlobberQuery) loadTaskArgs(ctx context.Context, query *TaskQuery, nodes []*Blobber, init func(*Blobber), assign func(*Blobber, *Task)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Blobber)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(task.FieldArgs)
	}
	query.Where(predicate.Task(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(blobber.TaskArgsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.Args
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "args" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (bq *BlobberQuery) loadTaskOutput(ctx context.Context, query *TaskQuery, nodes []*Blobber, init func(*Blobber), assign func(*Blobber, *Task)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Blobber)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(task.FieldOutput)
	}
	query.Where(predicate.Task(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(blobber.TaskOutputColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.Output
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "output" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (bq *BlobberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bq.querySpec()
	if len(bq.modifiers) > 0 {
		_spec.Modifiers = bq.modifiers
	}
	_spec.Node.Columns = bq.ctx.Fields
	if len(bq.ctx.Fields) > 0 {
		_spec.Unique = bq.ctx.Unique != nil && *bq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bq.driver, _spec)
}

func (bq *BlobberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(blobber.Table, blobber.Columns, sqlgraph.NewFieldSpec(blobber.FieldID, field.TypeInt))
	_spec.From = bq.sql
	if unique := bq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bq.path != nil {
		_spec.Unique = true
	}
	if fields := bq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blobber.FieldID)
		for i := range fields {
			if fields[i] != blobber.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bq *BlobberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bq.driver.Dialect())
	t1 := builder.Table(blobber.Table)
	columns := bq.ctx.Fields
	if len(columns) == 0 {
		columns = blobber.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bq.sql != nil {
		selector = bq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bq.ctx.Unique != nil && *bq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range bq.modifiers {
		m(selector)
	}
	for _, p := range bq.predicates {
		p(selector)
	}
	for _, p := range bq.order {
		p(selector)
	}
	if offset := bq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (bq *BlobberQuery) ForUpdate(opts ...sql.LockOption) *BlobberQuery {
	if bq.driver.Dialect() == dialect.Postgres {
		bq.Unique(false)
	}
	bq.modifiers = append(bq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return bq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (bq *BlobberQuery) ForShare(opts ...sql.LockOption) *BlobberQuery {
	if bq.driver.Dialect() == dialect.Postgres {
		bq.Unique(false)
	}
	bq.modifiers = append(bq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return bq
}

// BlobberGroupBy is the group-by builder for Blobber entities.
type BlobberGroupBy struct {
	selector
	build *BlobberQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bgb *BlobberGroupBy) Aggregate(fns ...AggregateFunc) *BlobberGroupBy {
	bgb.fns = append(bgb.fns, fns...)
	return bgb
}

// Scan applies the selector query and scans the result into the given value.
func (bgb *BlobberGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bgb.build.ctx, ent.OpQueryGroupBy)
	if err := bgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlobberQuery, *BlobberGroupBy](ctx, bgb.build, bgb, bgb.build.inters, v)
}

func (bgb *BlobberGroupBy) sqlScan(ctx context.Context, root *BlobberQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bgb.fns))
	for _, fn := range bgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bgb.flds)+len(bgb.fns))
		for _, f := range *bgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BlobberSelect is the builder for selecting fields of Blobber entities.
type BlobberSelect struct {
	*BlobberQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bs *BlobberSelect) Aggregate(fns ...AggregateFunc) *BlobberSelect {
	bs.fns = append(bs.fns, fns...)
	return bs
}

// Scan applies the selector query and scans the result into the given value.
func (bs *BlobberSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bs.ctx, ent.OpQuerySelect)
	if err := bs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlobberQuery, *BlobberSelect](ctx, bs.BlobberQuery, bs, bs.inters, v)
}

func (bs *BlobberSelect) sqlScan(ctx context.Context, root *BlobberQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bs.fns))
	for _, fn := range bs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
